import type { Response } from 'express';
import { z } from 'zod';
import type { AuthRequest } from '../lib/auth';
import { badRequest, conflict, notFound, param } from '../lib/http';
import { env } from '../lib/env';
import { prisma } from '../lib/prisma';
import { EvaluationQueue } from '../services/EvaluationQueue';
import { QuestionGenerationService } from '../services/QuestionGenerationService';
import { SchedulerService } from '../services/SchedulerService';
import { BotError, PLATFORM_LABEL } from '../services/meetingBot/errors';
import { driverFor, parseMeetingLink } from '../services/meetingBot/platforms';
import { MeetBotManager } from '../services/meetingBot/MeetBotManager';

/**
 * The recruiter-facing API for interviews the AI runs inside a meeting the
 * recruiter already created.
 *
 * The form is deliberately one screen — candidate, role, link, time — but each
 * submission produces the same objects the rest of the platform works with: a
 * session, a candidate, a question set and a transcript. Reports, analytics and
 * exports therefore work on these interviews with no special-casing anywhere.
 */

const createSchema = z.object({
  candidateName: z.string().min(2, 'Enter the candidate’s name'),
  candidateEmail: z.string().email('Enter a valid candidate email'),
  jobTitle: z.string().min(2, 'Enter the job title'),
  jobDescription: z
    .string()
    .min(30, 'The job description needs at least 30 characters to generate good questions'),
  requiredSkills: z.array(z.string().min(1)).min(1, 'List at least one required skill'),
  durationMinutes: z.coerce.number().int().min(10).max(180).default(30),
  meetLink: z.string().min(1, 'Paste the meeting link'),
  scheduledAt: z.string().min(1),

  experienceLevel: z.string().default('Mid-level (3-5 years)'),
  type: z.enum(['TECHNICAL', 'HR', 'MIXED']).default('MIXED'),
  personality: z.enum(['FRIENDLY', 'NEUTRAL', 'FORMAL', 'CHALLENGING']).default('FRIENDLY'),
  language: z.string().default('en-US'),
  passMark: z.coerce.number().int().min(1).max(10).default(6),
  /** Skip the invitation email when the recruiter has already sent the link. */
  sendInvite: z.boolean().default(true),
  /**
   * Include a coding exercise. A meeting call has no shared editor, so the
   * candidate opens a browser tab for it — the link is emailed with the
   * invitation and posted in the meeting chat when the round starts.
   */
  codingEnabled: z.boolean().default(false),
});

/**
 * Whether the coding editor page actually exists at APP_URL.
 *
 * This is the one link in the system that is generated by the backend but
 * served by the frontend, so the two can disagree — a backend running locally
 * against a deployment that predates the coding page hands the candidate a 404
 * in the middle of their interview, with no way to recover.
 *
 * The token in the probe URL is deliberately meaningless: a missing *route*
 * 404s for every token, and a present route renders for any of them, so this
 * answers "is the page deployed" without touching a real interview.
 *
 * Cached because it is the same answer for every interview on a given
 * deployment, and this runs on the interview page.
 */
let reachabilityCache: { at: number; ok: boolean } | null = null;
const REACHABILITY_TTL_MS = 60_000;

async function codingPageReachable(): Promise<boolean> {
  if (reachabilityCache && Date.now() - reachabilityCache.at < REACHABILITY_TTL_MS) {
    return reachabilityCache.ok;
  }

  let ok = false;
  try {
    const res = await fetch(`${env.APP_URL}/interview/reachability-probe/code`, {
      method: 'GET',
      redirect: 'follow',
      signal: AbortSignal.timeout(6_000),
    });
    ok = res.status === 200;
    if (!ok) {
      console.warn(
        `[config] the coding editor page is not deployed at ${env.APP_URL} (HTTP ${res.status}). ` +
          'Candidates will get a 404. Point APP_URL at a frontend that has it, or deploy the current build.',
      );
    }
  } catch {
    // Unreachable is not the same as absent, but the candidate cannot tell.
    ok = false;
  }

  reachabilityCache = { at: Date.now(), ok };
  return ok;
}

/**
 * Resolves the interview and proves the caller owns it.
 *
 * Every endpoint below runs this first: the id is a bare uuid in the URL, and
 * without the ownership clause any signed-in recruiter could read any
 * candidate's transcript.
 */
async function ownedInterview(req: AuthRequest, id: string) {
  const interview = await prisma.sessionCandidate.findFirst({
    where: { id, interviewSession: { userId: req.user!.userId } },
    include: {
      candidate: true,
      interviewSession: true,
      meetBotRun: true,
      report: { select: { id: true } },
      transcript: { select: { id: true, _count: { select: { turns: true } } } },
    },
  });

  if (!interview) throw notFound('Interview not found');
  return interview;
}

/**
 * Why there is, or is not, a report yet.
 *
 * Without this the dashboard can only say "no report", which covers a candidate
 * who never showed up, an interview that finished thirty seconds ago, and a
 * provider quota that will clear in twenty minutes. Those need three different
 * reactions from the recruiter, so they are told apart here.
 */
function evaluationState(interview: Awaited<ReturnType<typeof ownedInterview>>) {
  const turns = interview.transcript?._count.turns ?? 0;

  const state = interview.report
    ? 'READY'
    : interview.status === 'INCOMPLETE'
      ? 'NOT_SCORED_INCOMPLETE'
      : interview.status !== 'COMPLETED'
        ? 'NOT_INTERVIEWED'
        : turns === 0
          ? 'NO_TRANSCRIPT'
          : interview.evaluationRetryAt
            ? 'RETRYING'
            : interview.evaluationAttempts > 0
              ? 'FAILED'
              : 'PENDING';

  const EXPLANATION: Record<string, string> = {
    READY: 'The report is ready.',
    PENDING: 'The interview is finished; the report is being written.',
    RETRYING: 'Report generation hit a temporary problem and will be retried automatically.',
    FAILED: 'Report generation failed. Use Retry to try again.',
    NO_TRANSCRIPT: 'Nothing was said during the interview, so there is nothing to score.',
    NOT_INTERVIEWED: 'The interview has not finished yet.',
    NOT_SCORED_INCOMPLETE:
      'The candidate left before the interviewer finished. Partial interviews are not scored, because a low score caused by walking out would misrepresent them. The transcript is kept in full.',
  };

  return {
    state,
    explanation: EXPLANATION[state] ?? '',
    reportId: interview.report?.id ?? null,
    attempts: interview.evaluationAttempts,
    error: interview.evaluationError,
    nextRetryAt: interview.evaluationRetryAt,
    transcriptTurns: turns,
  };
}

/** The shape the dashboard renders. */
function present(interview: Awaited<ReturnType<typeof ownedInterview>>) {
  const run = interview.meetBotRun;
  const session = interview.interviewSession;

  return {
    id: interview.id,
    candidateName: interview.candidate.name,
    candidateEmail: interview.candidate.email,
    jobTitle: session.title,
    jobDescription: session.jobDescription,
    requiredSkills: session.skills,
    durationMinutes: session.durationMinutes,
    scheduledAt: session.scheduledAt,
    meetLink: run?.meetLink ?? session.meetingLink,
    platform: run?.platform ?? 'GOOGLE_MEET',
    platformLabel: PLATFORM_LABEL[(run?.platform ?? 'GOOGLE_MEET') as keyof typeof PLATFORM_LABEL] ?? 'Meeting',
    /** Whether this platform needs the bot signed in, for the setup hint. */
    requiresSignIn: (() => {
      try {
        return driverFor((run?.platform ?? 'GOOGLE_MEET') as never).requiresSignIn;
      } catch {
        return false;
      }
    })(),

    status: run?.status ?? 'SCHEDULED',
    statusDetail: run?.statusDetail ?? null,
    errorCode: run?.errorCode ?? null,
    errorMessage: run?.errorMessage ?? null,

    joinAt: run?.joinAt ?? null,
    startedAt: run?.startedAt ?? null,
    joinedAt: run?.joinedAt ?? null,
    endedAt: run?.endedAt ?? null,
    attempts: run?.attempts ?? 0,

    candidateStatus: interview.status,
    live: MeetBotManager.isRunning(interview.id),
    hasReport: Boolean(interview.report),
    evaluation: evaluationState(interview),
    sessionId: session.id,

    codingEnabled: session.codingEnabled,
    /**
     * Where the candidate writes their code. Surfaced so the recruiter can send
     * it themselves — the bot posts it in the meeting chat, but chat panels are
     * the flakiest part of every one of these clients and a recruiter with the
     * link in front of them is never stuck.
     */
    codingUrl: session.codingEnabled ? `${env.APP_URL}/interview/${interview.accessToken}/code` : null,
  };
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

export const createMeetInterview = async (req: AuthRequest, res: Response) => {
  const data = createSchema.parse(req.body);

  // Fail on the link before anything is written. A recruiter who mistyped it
  // should find out while the form is open, not at the scheduled time.
  let link;
  try {
    link = parseMeetingLink(data.meetLink);
  } catch (err) {
    throw badRequest(
      err instanceof BotError ? err.message : 'That is not a meeting link the AI interviewer can join',
    );
  }

  const scheduledAt = new Date(data.scheduledAt);
  if (Number.isNaN(scheduledAt.getTime())) throw badRequest('scheduledAt is not a valid date');

  const email = data.candidateEmail.trim().toLowerCase();

  // Candidates are shared across sessions, so the same person interviewed twice
  // keeps one record and one history.
  const candidate = await prisma.candidate.upsert({
    where: { email },
    create: { email, name: data.candidateName.trim() },
    update: { name: data.candidateName.trim() },
  });

  const session = await prisma.interviewSession.create({
    data: {
      userId: req.user!.userId,
      title: data.jobTitle.trim(),
      jobDescription: data.jobDescription,
      skills: data.requiredSkills.map((s) => s.trim()).filter(Boolean),
      experienceLevel: data.experienceLevel,
      type: data.type,
      scheduledAt,
      durationMinutes: data.durationMinutes,
      status: 'SCHEDULED',
      meetingProvider: link.platform,
      // The candidate is emailed the link they were given, not the web-client
      // URL the bot uses to get around Zoom's app launcher.
      meetingLink: link.displayUrl,
      personality: data.personality,
      language: data.language,
      passMark: data.passMark,
      // The coding round moves to a browser tab the candidate opens; recording
      // and video analysis have no client to capture from at all, so they stay
      // off rather than being silently ignored.
      codingEnabled: data.codingEnabled,
      recordingEnabled: false,
      videoAnalysisEnabled: false,
    },
  });

  const interview = await prisma.sessionCandidate.create({
    data: { interviewSessionId: session.id, candidateId: candidate.id },
  });

  await prisma.meetBotRun.create({
    data: {
      sessionCandidateId: interview.id,
      meetLink: link.displayUrl,
      platform: link.platform,
      status: 'SCHEDULED',
      // Early enough to be admitted, settled and waiting when the candidate
      // arrives, rather than knocking on the lobby door at the start time.
      joinAt: new Date(scheduledAt.getTime() - env.MEET_BOT_JOIN_LEAD_MINUTES * 60_000),
    },
  });

  // Several seconds of LLM work; the recruiter should not wait for it. The
  // state machine loads questions when the interview starts, by which point
  // this has long finished.
  void QuestionGenerationService.generateAndSave(session.id).catch((err) =>
    console.error(`[meet-interview] question generation failed for ${session.id}:`, err.message),
  );

  if (data.sendInvite) {
    await SchedulerService.scheduleFor(interview.id).catch((err) =>
      console.error(`[meet-interview] could not queue reminders for ${interview.id}:`, err.message),
    );
  }

  // Scheduled for now, or for less than the lead time away: start at once
  // rather than leaving the recruiter watching nothing until the next tick.
  void MeetBotManager.startIfDue(interview.id);

  const created = await ownedInterview(req, interview.id);

  res.status(201).json({
    ...present(created),
    // Checked here, while the recruiter is still looking at the form, because
    // finding out mid-interview that the editor 404s cannot be recovered from.
    codingUrlReachable: data.codingEnabled ? await codingPageReachable() : null,
  });
};

// ---------------------------------------------------------------------------
// Read
// ---------------------------------------------------------------------------

/**
 * What the bot is about to do, and whether it is actually able to.
 *
 * Auto-join only happens while the server is running, so "is it armed" is a
 * real question with a real answer, and one a recruiter should not have to read
 * server logs to get.
 */
export const getMeetBotQueue = async (_req: AuthRequest, res: Response) => {
  res.json({
    enabled: env.MEET_BOT_ENABLED,
    running: MeetBotManager.activeCount(),
    capacity: env.MEET_BOT_MAX_CONCURRENT,
    joinLeadMinutes: env.MEET_BOT_JOIN_LEAD_MINUTES,
    candidateWaitMinutes: env.MEET_BOT_CANDIDATE_WAIT_MINUTES,
    candidateGraceMinutes: env.MEET_BOT_CANDIDATE_GRACE_MINUTES,
    upcoming: await MeetBotManager.upcoming(10),
    serverTime: new Date().toISOString(),
  });
};

export const listMeetInterviews = async (req: AuthRequest, res: Response) => {
  const { status, search, limit = '50' } = req.query as Record<string, string>;
  const take = Math.min(200, Math.max(1, parseInt(limit, 10) || 50));

  const interviews = await prisma.sessionCandidate.findMany({
    where: {
      interviewSession: { userId: req.user!.userId },
      // Only interviews the bot drives; the built-in room has its own screens.
      meetBotRun: status ? { status: status as never } : { isNot: null },
      ...(search
        ? {
            OR: [
              { candidate: { name: { contains: search, mode: 'insensitive' as const } } },
              { candidate: { email: { contains: search, mode: 'insensitive' as const } } },
              { interviewSession: { title: { contains: search, mode: 'insensitive' as const } } },
            ],
          }
        : {}),
    },
    include: {
      candidate: true,
      interviewSession: true,
      meetBotRun: true,
      report: { select: { id: true } },
      transcript: { select: { id: true, _count: { select: { turns: true } } } },
    },
    orderBy: { interviewSession: { scheduledAt: 'desc' } },
    take,
  });

  res.json({ interviews: interviews.map(present) });
};

export const getMeetInterview = async (req: AuthRequest, res: Response) => {
  const interview = await ownedInterview(req, param(req, 'id'));
  const body = present(interview);

  res.json({
    ...body,
    codingUrlReachable: body.codingUrl ? await codingPageReachable() : null,
  });
};

/** Deliberately small: polled as a fallback whenever the socket is down. */
export const getMeetInterviewStatus = async (req: AuthRequest, res: Response) => {
  const interview = await ownedInterview(req, param(req, 'id'));
  const run = interview.meetBotRun;

  res.json({
    interviewId: interview.id,
    status: MeetBotManager.statusOf(interview.id) ?? run?.status ?? 'SCHEDULED',
    detail: run?.statusDetail ?? null,
    errorCode: run?.errorCode ?? null,
    errorMessage: run?.errorMessage ?? null,
    live: MeetBotManager.isRunning(interview.id),
    joinedAt: run?.joinedAt ?? null,
    startedAt: run?.startedAt ?? null,
    endedAt: run?.endedAt ?? null,
    // Drives the running clock in the dashboard without a second request.
    elapsedSeconds: run?.joinedAt
      ? Math.max(0, Math.floor(((run.endedAt ?? new Date()).getTime() - run.joinedAt.getTime()) / 1000))
      : 0,
  });
};

export const getMeetInterviewTranscript = async (req: AuthRequest, res: Response) => {
  const interview = await ownedInterview(req, param(req, 'id'));

  const transcript = await prisma.interviewTranscript.findUnique({
    where: { sessionCandidateId: interview.id },
    include: { turns: { orderBy: { timestamp: 'asc' } } },
  });

  let questionNumber = 0;

  res.json({
    interviewId: interview.id,
    candidateName: interview.candidate.name,
    summary: transcript?.summary ?? null,
    messages: (transcript?.turns ?? []).map((turn) => ({
      id: turn.id,
      speaker: turn.speaker,
      message: turn.text,
      timestamp: turn.timestamp,
      round: turn.round,
      // Numbered as they were asked, so a recruiter reading the transcript can
      // line it up with the question set.
      questionNumber: turn.speaker === 'AI' && turn.questionId ? ++questionNumber : null,
    })),
  });
};

// ---------------------------------------------------------------------------
// Control
// ---------------------------------------------------------------------------

export const startMeetInterview = async (req: AuthRequest, res: Response) => {
  const interview = await ownedInterview(req, param(req, 'id'));
  if (!interview.meetBotRun) throw badRequest('This interview has no Google Meet link attached');

  try {
    await MeetBotManager.start(interview.id, { manual: true });
  } catch (err) {
    if (err instanceof BotError) {
      // Capacity and "already running" are states of the world, not bad
      // requests; 409 lets the dashboard say so plainly.
      throw conflict(err.detail ? `${err.message} (${err.detail})` : err.message);
    }
    throw err;
  }

  res.json(present(await ownedInterview(req, interview.id)));
};

/**
 * Forces a fresh attempt at the report.
 *
 * The scheduler already retries on its own with backoff, but a recruiter
 * watching a provider quota tick down should not have to wait for the next
 * tick once it clears.
 */
export const retryMeetInterviewReport = async (req: AuthRequest, res: Response) => {
  const interview = await ownedInterview(req, param(req, 'id'));

  if (interview.report) {
    res.json({ ...evaluationState(interview), alreadyExisted: true });
    return;
  }

  if (interview.status !== 'COMPLETED') {
    throw conflict(
      interview.status === 'INCOMPLETE'
        ? 'This interview was not finished, so it is deliberately not scored.'
        : 'This interview has not been completed, so there is nothing to score yet.',
    );
  }

  // Clear the backoff first, or the queue will decline to run this attempt.
  await prisma.sessionCandidate.update({
    where: { id: interview.id },
    data: { evaluationRetryAt: null, evaluationAttempts: 0, evaluationError: null },
  });

  const ok = await EvaluationQueue.run(interview.id);
  res.json({ ...evaluationState(await ownedInterview(req, interview.id)), ranNow: ok });
};

export const stopMeetInterview = async (req: AuthRequest, res: Response) => {
  const interview = await ownedInterview(req, param(req, 'id'));
  const reason = String((req.body as { reason?: string })?.reason ?? 'Stopped from the dashboard').slice(0, 200);

  const stopped = await MeetBotManager.stop(interview.id, reason);
  if (!stopped) throw conflict('This interview is not running');

  res.json(present(await ownedInterview(req, interview.id)));
};
